// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"wb/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// GetOrderByID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetOrderByID(ctx context.Context, id string) (model.Order, bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 model.Order
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Order, bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOrderRepository_GetOrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByID'
type MockOrderRepository_GetOrderByID_Call struct {
	*mock.Call
}

// GetOrderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrderRepository_Expecter) GetOrderByID(ctx interface{}, id interface{}) *MockOrderRepository_GetOrderByID_Call {
	return &MockOrderRepository_GetOrderByID_Call{Call: _e.mock.On("GetOrderByID", ctx, id)}
}

func (_c *MockOrderRepository_GetOrderByID_Call) Run(run func(ctx context.Context, id string)) *MockOrderRepository_GetOrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetOrderByID_Call) Return(order model.Order, b bool, err error) *MockOrderRepository_GetOrderByID_Call {
	_c.Call.Return(order, b, err)
	return _c
}

func (_c *MockOrderRepository_GetOrderByID_Call) RunAndReturn(run func(ctx context.Context, id string) (model.Order, bool, error)) *MockOrderRepository_GetOrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// LoadCacheFromDB provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) LoadCacheFromDB(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadCacheFromDB")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_LoadCacheFromDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCacheFromDB'
type MockOrderRepository_LoadCacheFromDB_Call struct {
	*mock.Call
}

// LoadCacheFromDB is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderRepository_Expecter) LoadCacheFromDB(ctx interface{}) *MockOrderRepository_LoadCacheFromDB_Call {
	return &MockOrderRepository_LoadCacheFromDB_Call{Call: _e.mock.On("LoadCacheFromDB", ctx)}
}

func (_c *MockOrderRepository_LoadCacheFromDB_Call) Run(run func(ctx context.Context)) *MockOrderRepository_LoadCacheFromDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderRepository_LoadCacheFromDB_Call) Return(err error) *MockOrderRepository_LoadCacheFromDB_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_LoadCacheFromDB_Call) RunAndReturn(run func(ctx context.Context) error) *MockOrderRepository_LoadCacheFromDB_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) SaveOrder(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type MockOrderRepository_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *MockOrderRepository_Expecter) SaveOrder(ctx interface{}, order interface{}) *MockOrderRepository_SaveOrder_Call {
	return &MockOrderRepository_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, order)}
}

func (_c *MockOrderRepository_SaveOrder_Call) Run(run func(ctx context.Context, order model.Order)) *MockOrderRepository_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_SaveOrder_Call) Return(err error) *MockOrderRepository_SaveOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_SaveOrder_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *MockOrderRepository_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}
