// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderHandler creates a new instance of MockOrderHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderHandler {
	mock := &MockOrderHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderHandler is an autogenerated mock type for the OrderHandler type
type MockOrderHandler struct {
	mock.Mock
}

type MockOrderHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderHandler) EXPECT() *MockOrderHandler_Expecter {
	return &MockOrderHandler_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function for the type MockOrderHandler
func (_mock *MockOrderHandler) GetOrder(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockOrderHandler_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderHandler_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockOrderHandler_Expecter) GetOrder(w interface{}, r interface{}) *MockOrderHandler_GetOrder_Call {
	return &MockOrderHandler_GetOrder_Call{Call: _e.mock.On("GetOrder", w, r)}
}

func (_c *MockOrderHandler_GetOrder_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockOrderHandler_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderHandler_GetOrder_Call) Return() *MockOrderHandler_GetOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrderHandler_GetOrder_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockOrderHandler_GetOrder_Call {
	_c.Run(run)
	return _c
}
